In [35]:
import numpy as np

## Крассидис iphone

In [36]:
y = np.array([-0.334297385620915000, 15.798398692810500000, -52.381977124183000000]).reshape(3, 1)
h = np.array([-0.78272689, -0.21560676, -1.24611666]).reshape(3, 1)
T = np.array([0.86920035, -0.01633663, -0.00192375, -0.01633663, 0.91213618, 0.00311428, -0.00192375, 0.00311428, 0.88345968]).reshape(3, 3)

y_after = np.linalg.inv(T) @ (y - h)

print(y_after)
print('y_after.shape =', y_after.shape)

diff = y - y_after

print(diff)
print('diff.shape =', diff.shape)

[[  0.72160736]
 [ 17.76735032]
 [-57.94243465]]
y_after.shape = (3, 1)
[[-1.05590475]
 [-1.96895163]
 [ 5.56045753]]
diff.shape = (3, 1)


## Васконселас iphone

In [37]:
h = np.array([25.80209132, 33.81487825, 142.23953796]).reshape(3, 1)
T = np.array([-2.78787449e-06, -1.35573936e-05, 7.13014430e-06, 1.00739246e-04, 3.71584038e-04, -2.48157157e-04, -4.22630374e-05, -1.75755163e-04, 1.13677278e-04]).reshape(3, 3)

y_after = np.linalg.inv(T) @ (y - h)

print(y_after)
print('y_after.shape =', y_after.shape)

diff = y - y_after

print(diff)
print('diff.shape =', diff.shape)

[[-41214508.00014088]
 [  7726901.41657074]
 [ -5088343.07382355]]
y_after.shape = (3, 1)
[[41214507.66584349]
 [-7726885.61817205]
 [ 5088290.69184643]]
diff.shape = (3, 1)


## Крассидис android

In [38]:
y = np.array([0.500209389824975000, 17.524943562898800000, -49.680750858825300000]).reshape(3, 1)
h = np.array([-0.37483251, -1.07083444, -0.04395713]).reshape(3, 1)
T = np.array([0.86182819, -0.00918396, 0.00238145, -0.00918396, 0.89901625, 0.0079975, 0.00238145, 0.0079975, 0.86258483]).reshape(3, 3)

y_after = np.linalg.inv(T) @ (y - h)

print(y_after)
print('y_after.shape =', y_after.shape)

diff = y - y_after

print(diff)
print('diff.shape =', diff.shape)

[[  1.40094483]
 [ 21.21258449]
 [-57.74478744]]
y_after.shape = (3, 1)
[[-0.90073545]
 [-3.68764093]
 [ 8.06403658]]
diff.shape = (3, 1)
