In [1]:
import numpy as np

In [2]:
y = np.array([-9.27, -9.99, -53.38])
y.shape = (3, 1)
m = np.array([14396.4, 3025.4, 50837.1])
m.shape = (3, 1)
e = np.array([1, 1, 1])
e.shape = (3, 1)

O = np.zeros(9)

print(y)
print(m)

[[ -9.27]
 [ -9.99]
 [-53.38]]
[[14396.4]
 [ 3025.4]
 [50837.1]]


In [3]:
np.warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)

In [4]:
Z = np.linalg.norm(y) ** 2 - np.linalg.norm(m) ** 2

h = O[:3]
h.shape = (3, 1)
D = np.array([
  [O[3], O[6], O[7]],
  [O[6], O[4], O[8]],
  [O[7], O[8], O[5]]
])
print(h)
print(D)

S = np.transpose(np.concatenate((y ** 2, [
  2 * y[0] * y[1],
  2 * y[0] * y[2],
  2 * y[1] * y[2]
])))
print(S)

J = np.transpose(np.concatenate((y * h, [
  y[0] * h[1] + y[1] * h[0],
  y[0] * h[2] + y[2] * h[0],
  y[1] * h[2] + y[2] * h[1]
])))
print(J)

F = [
  [2 * (1 + D[0][0]),                 0,                 0,            2 * D[0][1],            2 * D[0][2],                      0],
  [                0, 2 * (1 + D[1][1]),                 0,            2 * D[0][1],                      0,            2 * D[1][2]],
  [                0,                 0, 2 * (1 + D[2][2]),                      0,            2 * D[0][2],            2 * D[1][2]],
  [          D[0][1],           D[0][1],                 0, 2  + D[0][0] + D[1][1],                D[1][2],                D[0][2]],
  [          D[0][2],                 0,           D[0][2],                D[1][2], 2  + D[0][0] + D[2][2],                D[0][1]],
  [                0,           D[1][2],           D[1][2],                D[0][2],                D[0][1], 2  + D[1][1] + D[2][2]]
]
print(F)

[[0.]
 [0.]
 [0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[  85.9329   99.8001 2849.4244  185.2146  989.6652 1066.5324]]
[[-0. -0. -0. -0. -0. -0.]]
[[2.0, 0, 0, 0.0, 0.0, 0], [0, 2.0, 0, 0.0, 0, 0.0], [0, 0, 2.0, 0, 0.0, 0.0], [0.0, 0.0, 0, 2.0, 0.0, 0.0], [0.0, 0, 0.0, 0.0, 2.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 2.0]]


In [5]:
H1 = np.matmul(2 * np.transpose(y), (np.identity(3) + D)) - 2 * np.transpose(h)
H2 = -np.matmul(S, F) + 2 * J

H = np.hstack((H1, H2))
print(H)
print(H.shape)

[[  -18.54     -19.98    -106.76    -171.8658  -199.6002 -5698.8488
   -370.4292 -1979.3304 -2133.0648]]
(1, 9)


In [6]:
P11 = 10 * np.identity(3)
P12 = np.zeros((3, 6))
P21 = np.zeros((6, 3))
P22 = 0.001 * np.identity(6)

P = np.vstack(( np.hstack((P11, P12)), np.hstack((P21, P22)) ))

print(P)

[[1.e+01 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 1.e+01 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 1.e+01 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03]]


In [7]:
SIGMA = 0.2522260688
IDyh = np.matmul((np.identity(3) + D), y) - h
sigma2 = 4 * SIGMA ** 2 * np.matmul(np.transpose(IDyh), IDyh) + 6 * SIGMA ** 4

print(sigma2)

K = np.matmul(
  np.matmul(P, np.transpose(H)),
  np.linalg.inv(
      np.matmul(
        np.matmul(H, P),
        np.transpose(H)
      )
    )
    + sigma2
)
print(K)
print(K.shape)

[[772.38673334]]
[[-1.43200502e+05]
 [-1.54322871e+05]
 [-8.24600083e+05]
 [-1.32746865e+02]
 [-1.54168548e+02]
 [-4.40171524e+03]
 [-2.86114602e+02]
 [-1.52880855e+03]
 [-1.64755097e+03]]
(9, 1)


In [8]:
fi = np.matmul(
  np.matmul(
    -np.transpose(y),
    2 * D + D ** 2
  ),
  y
) + np.matmul(
  np.matmul(
    2 * np.transpose(y),
    np.identity(3) + D
  ),
  h
) - np.linalg.norm(h) ** 2

print(fi)

[[0.]]


In [9]:
Ot = np.transpose(O)
Ot.shape = (9, 1)

O2 = Ot + np.matmul(K, Z - fi)
print(O2)

P2 = np.matmul(np.identity(9) - np.matmul(K, H), P)
print(P2)

[[4.01078410e+14]
 [4.32230132e+14]
 [2.30955400e+15]
 [3.71799686e+11]
 [4.31797901e+11]
 [1.23283992e+13]
 [8.01354664e+11]
 [4.28191311e+12]
 [4.61448888e+12]]
[[-2.65493630e+07 -2.86114602e+07 -1.52880855e+08 -2.46112688e+04
  -2.85828487e+04 -8.16078006e+05 -5.30456472e+04 -2.83441106e+05
  -3.05455949e+05]
 [-2.86114602e+07 -3.08336995e+07 -1.64755097e+08 -2.65228236e+04
  -3.08028758e+04 -8.79462706e+05 -5.71656975e+04 -3.05455949e+05
  -3.29180683e+05]
 [-1.52880855e+08 -1.64755097e+08 -8.80343039e+08 -1.41720553e+05
  -1.64590342e+05 -4.69927119e+06 -3.05455949e+05 -1.63215601e+06
  -1.75892541e+06]
 [-2.46112688e+04 -2.65228236e+04 -1.41720553e+05 -2.28136461e+01
  -2.64963008e+01 -7.56504312e+02 -4.91733150e+01 -2.62749905e+02
  -2.83157665e+02]
 [-2.85828487e+04 -3.08028758e+04 -1.64590342e+05 -2.64963008e+01
  -3.07710730e+01 -8.78583243e+02 -5.71085318e+01 -3.05150493e+02
  -3.28851502e+02]
 [-8.16078006e+05 -8.79462706e+05 -4.69927119e+06 -7.56504312e+02
  -8.78583243e+0