In [26]:
import numpy as np

In [27]:
y = np.array([-9.27, -9.99, -53.38])
y.shape = (3, 1)
m = np.array([14.3964, 30.25, 50.837])
m.shape = (3, 1)
e = np.array([1, 1, 1])
e.shape = (3, 1)

O = np.zeros(9)

print(y)
print(m)

[[ -9.27]
 [ -9.99]
 [-53.38]]
[[14.3964]
 [30.25  ]
 [50.837 ]]


In [28]:
np.warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)

In [29]:
Z = np.linalg.norm(y) ** 2 - np.linalg.norm(m) ** 2

h = O[:3]
h.shape = (3, 1)
D = np.array([
  [O[3], O[6], O[7]],
  [O[6], O[4], O[8]],
  [O[7], O[8], O[5]]
])
print(h)
print(D)

S = np.transpose(np.concatenate((y ** 2, [
  2 * y[0] * y[1],
  2 * y[0] * y[2],
  2 * y[1] * y[2]
])))
print(S)

J = np.transpose([
  y[0] * h[0],
  y[1] * h[1],
  y[2] * h[2],
  y[0] * h[1] + y[1] * h[0],
  y[0] * h[2] + y[2] * h[0],
  y[1] * h[2] + y[2] * h[1]
])
print(J)

F = [
  [2 * (1 + D[0][0]),                 0,                 0,            2 * D[0][1],            2 * D[0][2],                      0],
  [                0, 2 * (1 + D[1][1]),                 0,            2 * D[0][1],                      0,            2 * D[1][2]],
  [                0,                 0, 2 * (1 + D[2][2]),                      0,            2 * D[0][2],            2 * D[1][2]],
  [          D[0][1],           D[0][1],                 0, 2  + D[0][0] + D[1][1],                D[1][2],                D[0][2]],
  [          D[0][2],                 0,           D[0][2],                D[1][2], 2  + D[0][0] + D[2][2],                D[0][1]],
  [                0,           D[1][2],           D[1][2],                D[0][2],                D[0][1], 2  + D[1][1] + D[2][2]]
]
print(F)

[[0.]
 [0.]
 [0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[  85.9329   99.8001 2849.4244  185.2146  989.6652 1066.5324]]
[[-0. -0. -0. -0. -0. -0.]]
[[2.0, 0, 0, 0.0, 0.0, 0], [0, 2.0, 0, 0.0, 0, 0.0], [0, 0, 2.0, 0, 0.0, 0.0], [0.0, 0.0, 0, 2.0, 0.0, 0.0], [0.0, 0, 0.0, 0.0, 2.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 2.0]]


In [30]:
H1 = np.matmul(2 * np.transpose(y), (np.identity(3) + D)) - 2 * np.transpose(h)
H2 = -np.matmul(S, F) + 2 * J

H = np.hstack((H1, H2))
print(H)
print(H.shape)

[[  -18.54     -19.98    -106.76    -171.8658  -199.6002 -5698.8488
   -370.4292 -1979.3304 -2133.0648]]
(1, 9)


In [31]:
P11 = 10 * np.identity(3)
P12 = np.zeros((3, 6))
P21 = np.zeros((6, 3))
P22 = 0.001 * np.identity(6)

P = np.vstack(( np.hstack((P11, P12)), np.hstack((P21, P22)) ))

print(P)

[[1.e+01 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 1.e+01 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 1.e+01 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03]]


In [32]:
SIGMA = 0.2522260688
IDyh = np.matmul((np.identity(3) + D), y) - h
sigma2 = 4 * SIGMA ** 2 * np.matmul(np.transpose(IDyh), IDyh) + 6 * SIGMA ** 4

print(sigma2)

K = np.matmul(
  np.matmul(P, np.transpose(H)),
  np.linalg.inv(
      np.matmul(
        np.matmul(H, P),
        np.transpose(H)
      ) + sigma2
    )
)
print(K)
print(K.shape)

[[772.38673334]]
[[-1.13512611e-03]
 [-1.22329124e-03]
 [-6.53646511e-03]
 [-1.05226190e-06]
 [-1.22206795e-06]
 [-3.48916508e-05]
 [-2.26798196e-06]
 [-1.21186063e-05]
 [-1.30598573e-05]]
(9, 1)


In [33]:
fi = np.matmul(
  np.matmul(
    -np.transpose(y),
    2 * D + D ** 2
  ),
  y
) + np.matmul(
  np.matmul(
    2 * np.transpose(y),
    np.identity(3) + D
  ),
  h
) - np.linalg.norm(h) ** 2

print(fi)

[[0.]]


In [34]:
Ot = np.transpose(O)
Ot.shape = (9, 1)

print(Z)

O2 = Ot + np.matmul(K, Z - fi)
print(O2)

P2 = np.matmul(np.identity(9) - np.matmul(K, H), P)
print(P2)

-671.5620019600001
[[7.62307560e-01]
 [8.21515915e-01]
 [4.38964159e+00]
 [7.06659109e-04]
 [8.20694399e-04]
 [2.34319068e-02]
 [1.52309051e-03]
 [8.13839552e-03]
 [8.77050391e-03]]
[[ 9.78954762e+00 -2.26798196e-01 -1.21186063e+00 -1.95089356e-04
  -2.26571398e-04 -6.46891205e-03 -4.20483855e-04 -2.24678961e-03
  -2.42129754e-03]
 [-2.26798196e-01  9.75558641e+00 -1.30598573e+00 -2.10241928e-04
  -2.44169176e-04 -6.97135182e-03 -4.53142796e-04 -2.42129754e-03
  -2.60935949e-03]
 [-1.21186063e+00 -1.30598573e+00  3.02166985e+00 -1.12339481e-03
  -1.30467974e-03 -3.72503263e-02 -2.42129754e-03 -1.29378241e-02
  -1.39427036e-02]
 [-1.95089356e-04 -2.10241928e-04 -1.12339481e-03  9.99819152e-04
  -2.10031686e-07 -5.99668147e-06 -3.89788534e-07 -2.08277397e-06
  -2.24454282e-06]
 [-2.26571398e-04 -2.44169176e-04 -1.30467974e-03 -2.10031686e-07
   9.99756075e-04 -6.96438047e-06 -4.52689653e-07 -2.41887624e-06
  -2.60675013e-06]
 [-6.46891205e-03 -6.97135182e-03 -3.72503263e-02 -5.99668147e-