In [28]:
import numpy as np

In [29]:
y = np.array([-9.27, -9.99, -53.38])
m = np.array([14396.4, 3025.4, 50837.1])
e = np.array([1, 1, 1])

O = np.zeros(9)

In [30]:
np.warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)

In [68]:
Z = np.linalg.norm(y) ** 2 - np.linalg.norm(m) ** 2

h = O[:3]
D = np.array([
  [O[3], O[6], O[7]],
  [O[6], O[4], O[8]],
  [O[7], O[8], O[5]]
])
print(h)
print(D)

S = np.concatenate((y ** 2, [
  2 * y[0] * y[1],
  2 * y[0] * y[2],
  2 * y[1] * y[2]
]))
print(S)

J = np.concatenate((y * h, [
  y[0] * h[1] + y[1] * h[0],
  y[0] * h[2] + y[2] * h[0],
  y[1] * h[2] + y[2] * h[1]
]))
print(J)

F = [
  [2 * (1 + D[0][0]),                 0,                 0,            2 * D[0][1],            2 * D[0][2],                      0],
  [                0, 2 * (1 + D[1][1]),                 0,            2 * D[0][1],                      0,            2 * D[1][2]],
  [                0,                 0, 2 * (1 + D[2][2]),                      0,            2 * D[0][2],            2 * D[1][2]],
  [          D[0][1],           D[0][1],                 0, 2  + D[0][0] + D[1][1],                D[1][2],                D[0][2]],
  [          D[0][2],                 0,           D[0][2],                D[1][2], 2  + D[0][0] + D[2][2],                D[0][1]],
  [                0,           D[1][2],           D[1][2],                D[0][2],                D[0][1], 2  + D[1][1] + D[2][2]]
]
print(F)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[  85.9329   99.8001 2849.4244  185.2146  989.6652 1066.5324]
[-0. -0. -0. -0. -0. -0.]
[[2.0, 0, 0, 0.0, 0.0, 0], [0, 2.0, 0, 0.0, 0, 0.0], [0, 0, 2.0, 0, 0.0, 0.0], [0.0, 0.0, 0, 2.0, 0.0, 0.0], [0.0, 0, 0.0, 0.0, 2.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 2.0]]


In [69]:
H11 = 2 * np.transpose(y) * (np.identity(3) + D)
H12 = np.zeros((3, 6))
H21 = np.zeros((6, 3))
H22 = -S * F + 2 * J

H = np.vstack(( np.hstack((H11, H12)), np.hstack((H21, H22)) ))
print(H)

[[  -18.54      -0.        -0.         0.         0.         0.
      0.         0.         0.    ]
 [   -0.       -19.98      -0.         0.         0.         0.
      0.         0.         0.    ]
 [   -0.        -0.      -106.76       0.         0.         0.
      0.         0.         0.    ]
 [    0.         0.         0.      -171.8658    -0.        -0.
     -0.        -0.        -0.    ]
 [    0.         0.         0.        -0.      -199.6002    -0.
     -0.        -0.        -0.    ]
 [    0.         0.         0.        -0.        -0.     -5698.8488
     -0.        -0.        -0.    ]
 [    0.         0.         0.        -0.        -0.        -0.
   -370.4292    -0.        -0.    ]
 [    0.         0.         0.        -0.        -0.        -0.
     -0.     -1979.3304    -0.    ]
 [    0.         0.         0.        -0.        -0.        -0.
     -0.        -0.     -2133.0648]]


In [63]:
P11 = 10 * np.identity(3)
P12 = np.zeros((3, 6))
P21 = np.zeros((6, 3))
P22 = 0.001 * np.identity(6)

P = np.vstack(( np.hstack((P11, P12)), np.hstack((P21, P22)) ))

print(P)

[[1.e+01 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 1.e+01 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 1.e+01 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03 0.e+00]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e-03]]


In [78]:
SIGMA = 0.2522260688
sigma2 = 4 * SIGMA ** 2 * np.transpose((np.identity(3) + D) * y - h) * ((np.identity(3) + D) * y - h) + 6 * SIGMA ** 4

print(sigma2)

# K = P * np.transpose(H) * np.linalg.inv(H * P * np.transpose(H) + sigma2)
print((H * P * np.transpose(H)).shape)

[[2.18917969e+01 2.42834917e-02 2.42834917e-02]
 [2.42834917e-02 2.54206105e+01 2.42834917e-02]
 [2.42834917e-02 2.42834917e-02 7.25122893e+02]]
(9, 9)
