In [7]:
import numpy as np

a = np.matrix([[1], [2], [3], [4]])
b = np.matrix([1, 2, 3])

print(a.shape, b.shape)
print(np.tensordot(a, b, axes=0))
print(np.kron(a, b))

(4, 1) (1, 3)
[[[[ 1  2  3]]]


 [[[ 2  4  6]]]


 [[[ 3  6  9]]]


 [[[ 4  8 12]]]]
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]
