In [45]:
import numpy as np
import csv

# 0-x
# 1-y
# 2-z
y = []

with open('dist/iphone-calibration.csv', 'r') as fr:
  csvreader = csv.reader(fr, delimiter=';')

  index = 0
  for row in csvreader:
    index += 1
    if index == 1:
      continue

    y.append(list(map(lambda v: float(v.replace(',', '.')), row[1:4])))

y = np.array(y)
print(y[:5])
print('y.shape =', y.shape)

[[ -8.88  -9.54 -53.26]
 [ -9.27  -9.99 -53.38]
 [ -9.74  -9.48 -53.38]
 [-11.31  -8.79 -53.2 ]
 [-15.44  -6.52 -52.3 ]]
y.shape = (603, 3)


In [42]:
L = []
for r in y:
  L.append([ r[0]**2, r[0]*r[1], r[0]*r[2], r[1]**2, r[1]*r[2], r[0], r[1], r[2], 1 ])
L = np.array(L)
print(L[:5])
print('L.shape =', L.shape)

[[ 78.8544  84.7152 472.9488  91.0116 508.1004  -8.88    -9.54   -53.26
    1.    ]
 [ 85.9329  92.6073 494.8326  99.8001 533.2662  -9.27    -9.99   -53.38
    1.    ]
 [ 94.8676  92.3352 519.9212  89.8704 506.0424  -9.74    -9.48   -53.38
    1.    ]
 [127.9161  99.4149 601.692   77.2641 467.628  -11.31    -8.79   -53.2
    1.    ]
 [238.3936 100.6688 807.512   42.5104 340.996  -15.44    -6.52   -52.3
    1.    ]]
L.shape = (603, 9)


In [44]:
b = np.array(list(map(lambda r: r[2]**2, y)))
b.shape = (b.shape[0], 1)
print(b[:5])
print('b.shape =', b.shape)

[[2836.6276]
 [2849.4244]
 [2849.4244]
 [2830.24  ]
 [2735.29  ]]
b.shape = (603, 1)
