In [39]:
import numpy as np
import csv

# 0-x
# 1-y
# 2-z
y = []

with open('dist/iphone-calibration.csv', 'r') as fr:
  csvreader = csv.reader(fr, delimiter=';')

  index = 0
  for row in csvreader:
    index += 1
    if index == 1:
      continue

    y.append(list(map(lambda v: float(v.replace(',', '.')), row[1:4])))

y = np.array(y)
print(y[:5])
print('y.shape =', y.shape)

[[ -8.88  -9.54 -53.26]
 [ -9.27  -9.99 -53.38]
 [ -9.74  -9.48 -53.38]
 [-11.31  -8.79 -53.2 ]
 [-15.44  -6.52 -52.3 ]]
y.shape = (603, 3)


In [40]:
L = []
for r in y:
  L.append([ r[0]**2, r[0]*r[1], r[0]*r[2], r[1]**2, r[1]*r[2], r[0], r[1], r[2], 1 ])
L = np.array(L)
print(L[:5])
print('L.shape =', L.shape)

[[ 78.8544  84.7152 472.9488  91.0116 508.1004  -8.88    -9.54   -53.26
    1.    ]
 [ 85.9329  92.6073 494.8326  99.8001 533.2662  -9.27    -9.99   -53.38
    1.    ]
 [ 94.8676  92.3352 519.9212  89.8704 506.0424  -9.74    -9.48   -53.38
    1.    ]
 [127.9161  99.4149 601.692   77.2641 467.628  -11.31    -8.79   -53.2
    1.    ]
 [238.3936 100.6688 807.512   42.5104 340.996  -15.44    -6.52   -52.3
    1.    ]]
L.shape = (603, 9)


In [41]:
b = np.array(list(map(lambda r: r[2]**2, y)))
b.shape = (b.shape[0], 1)
print(b[:5])
print('b.shape =', b.shape)

[[2836.6276]
 [2849.4244]
 [2849.4244]
 [2830.24  ]
 [2735.29  ]]
b.shape = (603, 1)


In [42]:
p = np.matmul(
  np.matmul(
    np.linalg.inv(
      np.matmul(np.transpose(L), L)
    ),
    np.transpose(L)
  ),
  b
)

print(p)
print('p.shape =', p.shape)

[[-1.04064464e+00]
 [-6.84464199e-02]
 [-7.72773853e-03]
 [-9.40092178e-01]
 [ 1.35881364e-02]
 [-1.83447201e+00]
 [-4.46200000e-01]
 [-2.18026360e+00]
 [ 2.88821886e+03]]
p.shape = (9, 1)


In [43]:
A, B, C, D, E, G, H, I, J = np.transpose(p)[0]
print(A, B, C, D, E, G, H, I, J)

-1.0406446423654294 -0.06844641988586858 -0.007727738528614053 -0.9400921775591867 0.013588136404898206 -1.8344720139405624 -0.4462000001755859 -2.1802636033761686 2888.2188567120743


In [44]:
alpha1 = -B**2 + D*C**2 + 4*D*A + A*E**2 - B*E*C

alpha2 = 4*A*E**2*J - E**2*G**2 - 4*B*E*C*J + 2*E*C*H*D + \
  2*B*E*I*G - 4*E*H*A*I - 4*D*I*C*G - C**2*H**2 + \
  4*D*A*I**2 + 2*C*B*H*I - 4*D*G**2 + 4*D*C**2*J + \
  4*B*H*G - 4*A*H**2 - B**2*I**2 - 4*B**2*J + 16*D*A*J

alpha3 = E**4*A - C*B*E**3 + E**2*C**2*D - 2*B**2*E**2 + \
  8*D*A*E**2 - 4*D*B**2 + 16*D**2*A

print('alpha1 =', alpha1)
print('alpha2 =', alpha2)
print('alpha3 =', alpha3)

beta1 = 2*B*H + B*E*I - 2*C*D*I - 4*D*G + E*C*H - E**2*G
beta2 = -2*A*E*I + 4*A*H - B*C*I - 2*B*G + C**2*H - C*E*G
beta3 = 4*D*I*A - 2*D*G*C + E*G*B - I*B**2 - 2*E*H*A + C*B*H

print('beta1 =', beta1)
print('beta2 =', beta2)
print('beta3 =', beta3)

alpha1 = 3.908267169631295
alpha2 = 45183.49413157619
alpha3 = -14.696042963672262
beta1 = -6.803117936395392
beta2 = 1.545490727016449
beta3 = -8.506104313632525


In [45]:
_a = 1 / (2 * alpha1) * (-(4*D + E**2) * alpha2)**0.5
_b = 1 / (2 * alpha1) * (-(4*A + C**2) * alpha2)**0.5
_c = 1 / (2 * alpha1) * ((4*D*A - B**2) * alpha2)**0.5

print('_a =', _a)
print('_b =', _b)
print('_c =', _c)

tanpi = -1 / (2 * alpha1) * (2*B + E*C) * alpha1**(-0.5)
tanphi = (B*E - 2*C*D) * alpha1**(-0.5)
tanla = E * (-alpha1*alpha3**(-1))**0.5

print('tanpi =', tanpi)
print('tanphi =', tanphi)
print('tanla =', tanla)

pi = np.arctan(tanpi)
phi = np.arctan(tanphi)
la = np.arctan(tanla)

print('pi =', pi)
print('phi =', phi)
print('la =', la)

secpi = 1 / np.cos(pi)
secphi = 1 / np.cos(phi)
secla = 1 / np.cos(la)

print('secpi =', secpi)
print('secphi =', secphi)
print('secla =', secla)

_a = 52.732725559984516
_b = 55.482212695833915
_c = 53.762812774808914
tanpi = 0.008865584516980909
tanphi = -0.007820005166541258
tanla = 0.007007317789431428
pi = 0.00886535225379009
phi = -0.007819845768151168
la = 0.00700720310053032
secpi = 1.000039298522227
secphi = 1.0000305757729633
secla = 1.0000245509499266


In [46]:
T0 = np.array([
  [ 1/_a, 0, 0],
  [ -1/_a * tanpi, -1/_b * secpi, 0],
  [
    1/_a * (tanpi*tanla*secphi - tanphi),
    -1/_b * secpi * tanla * secphi,
    1/_c * secla * secphi
  ],
])
print(T0)
print('T0.shape =', T0.shape)

h0 = 1/(2 * alpha1) * np.array([beta1, beta2, beta3])
h0.shape = (3, 1)
print(h0)
print('h0.shape =', h0.shape)

[[ 0.01896356  0.          0.        ]
 [-0.00016812 -0.0180245   0.        ]
 [ 0.00014947 -0.00012631  0.01860124]]
T0.shape = (3, 3)
[[-0.87034965]
 [ 0.19772071]
 [-1.0882194 ]]
h0.shape = (3, 1)


In [47]:
x1 = np.matrix(T0).flatten()
x2 = np.transpose(h0)

x = np.transpose(np.hstack((x1, x2)))

print(x)
print('x.shape =', x.shape)

[[ 1.89635561e-02]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.68123009e-04]
 [-1.80245028e-02]
 [ 0.00000000e+00]
 [ 1.49473234e-04]
 [-1.26307281e-04]
 [ 1.86012427e-02]
 [-8.70349651e-01]
 [ 1.97720711e-01]
 [-1.08821940e+00]]
x.shape = (12, 1)


In [48]:
# SIGMA = 0.2522260688
# IDyh = np.matmul((np.identity(3) + D), y) - h
# sigma2 = 4 * SIGMA ** 2 * np.matmul(np.transpose(IDyh), IDyh) + 6 * SIGMA ** 4
sigma2 = 1 # 🤷‍♂️ старая формула не подходит

In [55]:
T_circum = np.linalg.inv(T0)
print(T_circum)
print('T_circum.shape =', T_circum.shape)

should_log = True
def get_ck_uk(k):
  global should_log

  yk = y[k]
  yk.shape = (3, 1)

  uk = yk - h0

  ck = 1 - np.linalg.norm(
    np.matmul(T_circum, uk)
  )**(-1)

  if should_log:
    should_log = False
    print(yk)
    print('yk.shape =', yk.shape)
    print(uk)
    print('uk.shape =', uk.shape)
    print('ck =', ck)

  return (ck, uk)

ck, uk = get_ck_uk(0)
grad_T_circum = np.meshgrid(2 * ck / sigma2 * uk, np.matmul(T_circum, uk))
for k in range(1, len(y)):
  ck, uk = get_ck_uk(k)
  grad_T_circum += np.meshgrid(2 * ck / sigma2 * uk, np.matmul(T_circum, uk))

# print(grad_T_circum) ❌ WRONG 

[[ 52.73272556   0.           0.        ]
 [ -0.49186292 -55.48003241  -0.        ]
 [ -0.42708205  -0.37672387  53.75984913]]
T_circum.shape = (3, 3)
[[ -8.88]
 [ -9.54]
 [-53.26]]
yk.shape = (3, 1)
[[ -8.00965035]
 [ -9.73772071]
 [-52.1717806 ]]
uk.shape = (3, 1)
ck = 0.9996529247834629


In [ ]:
# x_next = x - np.linalg.inv(hessian(x)) * np.gradient(x)